# Generated by Django 4.0.1 on 2022-01-31 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='Weapons',
            new_name='Weapon',
        ),
    ]
