# Generated by Django 4.0.1 on 2022-01-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0002_rename_items_item_rename_weapons_weapon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('layout', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
