# Generated by Django 4.0.1 on 2022-02-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0003_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=256)),
            ],
        ),
    ]
