# Generated by Django 4.0.1 on 2022-02-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0004_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='inventory',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='player',
            name='left_hand',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='player',
            name='right_hand',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
