# Generated by Django 4.0.2 on 2022-02-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0005_player_inventory_player_left_hand_player_right_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='combat',
            field=models.BooleanField(default=False),
        ),
    ]
