# Generated by Django 4.0.2 on 2022-02-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0006_player_combat'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='end_game',
            field=models.BooleanField(default=False),
        ),
    ]
